### ISSUE TITLE
HmIP-PMFS

### ISSUE THREAD

**Issue by drMaxxi** [HM-RedMatic/RedMatic-HomeKit#101]
Könntest du bitte noch dieses Gerät hinzufügen? Danke!

**Comment by hobbyquaker** [comment]
@drMaxxi Da es keine HomeKit Charactersitic für "Netzausfall" gibt könnte man den nur als z.B. Fensterkontakt abbilden, das find ich aber "unschön", möcht ich nicht per Default so einbauen. Du kannst ihn allerdings mit dem "Universal Accessory" selbst auf beliebige HomeKit Services mappen und so integrieren.
