### ISSUE TITLE
implement HMW-Sen-SC-12-DR

### ISSUE THREAD

**Issue by spiu16** [HM-RedMatic/RedMatic-HomeKit#103]
Hallo,
kannst Du bitte den RS485 Schließerkontakt 12 Eingänge mit integrieren? Habe Fenster-/Türenkontakte damit angeschlossen und möchte diese auch gerne in HomeKit sichtbar haben.
Danke :)

**Comment by spiu16** [comment]
Danke für die schnelle Integration! Nur leider sind die Stati der Kontakte vertauscht, d.h. Status „offen“ ist tatsächlich „geschlossen“, „geschlossen“ ist tatsächlich „offen“. Kann ich das selbst ändern?

**Comment by hobbyquaker** [comment]
Oh. Ich machs in der nächsten Version konfigurierbar. Wenn Du es gleich ändern willst vertausche in der Datei `/usr/local/addons/redmatic/var/node_modules/redmatic-homekit/homematic-devices/hmw-sen-sc-12-dr.js` in den Zeilen 11 und 26 jeweils `CONTACT_DETECTED` und `CONTACT_NOT_DETECTED`

**Comment by spiu16** [comment]
Ok, wie kann ich das ändern? Zugriff per SSH mit User „root“ auf den Pi (Raspberrymatic). Und dann? Mit „nano“ klappt das nicht :-(
Danke vorab!

**Comment by spiu16** [comment]
hat sich erledigt, hab es mit vi hinbekommen manuell zu ändern.
