### ISSUE TITLE
Kein QR-Code

### ISSUE THREAD

**Issue by offbIRol** [HM-RedMatic/RedMatic-HomeKit#109]
Hallo,
Ich habe Probleme beim Einrichten des RedMatic-Homekit Nodes.
Es ist eine frische Installation von Raspberrymatic auf einem ThinkerBoard S 
die über LAN mit einer CCU3 verbunden ist, die IP-Adressen passen. Ich gehe vor wie im Wiki beschrieben, aber der QR-Code erscheint nicht. 
Dann lösche ich den Node und drücke auf"Deploy", dann kommt oben die Meldung über
"unused Configuration". Ich klicke drauf um zu löschen, dann ist der QR-Code da !!!
Den dann eingescannt in der Home App, es erscheint auch das Icon aber ich kann dann nichts mehr damit machen. Von allem die neueste Version installiert.

**Comment by hobbyquaker** [comment]
Lösch mal alle HomeKit-Homematic Nodes und auch alle Configuration Nodes (via Hamburger-Menü oben rechts -> configuration nodes, per doppelklick öffnen, oben links auf delete). Dann Deploy. Dann Node-RED neustarten. Dann erneut einen Homekit-Homematic Node einfügen, eine Bridge anlegen, Deploy. Ne Minute warten. Nochmal in den Bridge Config Node gehen und der QR Code sollte da sein.

**Comment by offbIRol** [comment]
Also ich hab alles genau so gemacht (ein paar mal hintereinander...), habs auch nochmal neu installiert aber es funktioniert nicht. Beim Node selber, ist unten ein gelbes Kästchen und "partly connected" als Status. Hat das vielleicht mit den Port's zu tun, Port 51826 bei der Bridge und 2087, 2088 bei CCU Connection?

**Comment by hobbyquaker** [comment]
@offbIRol dieser Issue ist mir irgendwie "hinten runter gefallen", sorry. Möchtest Du hier noch Support oder hat es vielleicht sogar mittlerweile geklappt?

**Comment by offbIRol** [comment]
Hallo,
Vielen Dank ich benötige momentan KEINEN Support wegen Zeitmangel.

**Comment by heilerich** [comment]
Ich danke schonmal, bei mir war genau das das Problem. HmIP war aktiviert, obwohl ich es nicht benutze und deshalb startete die bridge nicht.

**Comment by mludi** [comment]
Sorry war zwischendurch im Urlaub. Habe jetzt gemerkt, dass der PI sich komplett ausschaltet nach 2-3 Stunden. Vermutlich die SD Karte oder das Funkmodul oder der PI an sich defekt. Habe im Raspberrymatic zuletzt dann auch overheating warnings gesehen. Mal schauen ;)

**Comment by mludi** [comment]
So, um das jetzt abzuschließen. Habe mir jetzt das RPI-RF-MOD bestellt, verlötet eingebaut. Schon mal viel besser. Raspberrymatic komplett neu installiert auf eine andere SD-Karte, alles brav neu angelernt und eingerichtet. Siehe da, HomeKit läuft wieder wie es soll 👍  Danke für die Hilfe :-)
