### ISSUE TITLE
HmIP-SAM

### ISSUE THREAD

**Issue by Boarder** [HM-RedMatic/RedMatic-HomeKit#110]
Hi
der Aktor wird als solches erkannt. Ich habe ihn als Lagesensor in der CCu3 konfiguriert und es wäre super wenn er diesen Status "auf/zu" auch an Homekit übermitteln würde.

1000 Dank

**Comment by hobbyquaker** [comment]
@Boarder sollte in RedMatic v2.3.0 funktionieren, bitte gib Bescheid ob alles passt.

**Comment by Boarder** [comment]
@hobbyquaker Mega, perfekt. :-)

Vielen Dank für die schnelle Umsetzung.
