### ISSUE TITLE
Richtungswechsel bei HM-LC-Bl1PBU-FM

### ISSUE THREAD

**Issue by Jemeins** [HM-RedMatic/RedMatic-HomeKit#121]
Moin,
ich habe so eben das neuste Update gemacht, beim testen der Rollladenaktoren ist mir aufgefallen das beim öffnen oder schließen ein erneutes drücken in HomeKit nicht mehr zum Richtungswechsel führt. 
Mit freundlichen Grüßen 
Jendrik

**Comment by hobbyquaker** [comment]
@Jemeins Hab das eben versucht zu reproduzieren, gelang mir nicht, bei mir führt der erneute Druck nach wie vor zum Richtungswechsel. Hab es mit BidCos-RF Rollläden getestet, nutzt Du BidCos oder HmIP Rollläden? Sind es Rollladen oder Jalousie Aktoren? (Genau Aktorbezeichnung?)
Um das zu analysieren bin ich auf Deine Hilfe angewiesen. Leg mal bitte ein Flow an um die Nachrichten die der Rollladen sendet anzuschauen, so in der Art: 
![image](https://user-images.githubusercontent.com/2503307/52910615-57bf0680-329a-11e9-82b6-b95b22973a51.png)
(Den Debug Knoten auf "Complete Message Object" konfigurieren)
Von Bedeutung ist dann welche Nachrichten da rauskommen wenn Du den Rollladen fährst und dann während der Fahrt wieder in Homekit bedienst, speziell ob das Attribut `stable` richtig gesetzt ist. Das muss `true` sein wenn der Rollladen noch fährt und `false` nachdem er zum Stillstand gekommen ist.

**Comment by Jemeins** [comment]
Moin,
Ich nutze BidCos Rollladen Aktoren (HM-LC-Bl1PBU-FM).
Den Flow habe ich erstellt, beim erneuten betätigen in der Home App bekomme ich allerdings keine Debug Nachricht, wenn ich ein zweites mal drücke bekomme ich folgende Nachricht:

{"topic":"localhost/BidCos-RF/Jendriks Zimmer/LEVEL","payload":0.815,"ccu":"localhost","iface":"BidCos-RF","device":"OEQ0888821","deviceName":"Jendriks Zimmer","deviceType":"HM-LC-Bl1PBU-FM","channel":"OEQ0888821:1","channelName":"Jendriks Zimmer","channelType":"BLIND","channelIndex":1,"datapoint":"LEVEL","datapointName":"BidCos-RF.OEQ0888821:1.LEVEL","datapointType":"FLOAT","datapointMin":0,"datapointMax":1,"datapointDefault":0,"datapointControl":"BLIND.LEVEL","value":0.815,"valuePrevious":1,"valueStable":0.815,"rooms":["Jendriks Zimmer"],"room":"Jendriks Zimmer","functions":["Rollladen"],"function":"Rollladen","ts":1550403700487,"tsPrevious":1550403695039,"lc":1550403700487,"change":true,"cache":false,"working":true,"direction":2,"stable":false,"_msgid":"f0bfe8a5.dbba58"}

In der Home App sieht es bei mir wie folgt aus: 

Der Rollladen ist geöffnet, beim drücken wird er geschlossen ->
Der Rollladen fährt runter, beim erneuten drücken wird in Home Geöffnet angezeigt, der Rollladen fährt jedoch weiter runter ->
Ein erneutes drücken führt nur dazu das in der Home App schließen angezeigt wird. ->
Beim nächsten drücken wird Geöffnet angezeigt und der Rollladen fährt nach oben.

Mit freundlichen Grüßen 
Jendrik

**Comment by hobbyquaker** [comment]
@Jemeins gib mal bitte Bescheid ob sich das mit RedMatic 2.7.0 gebessert hat.

**Comment by Jemeins** [comment]
Moin,
erst mal vielen Dank!
Die Richtungsumkehr funktioniert wieder super!
Nach dem erneuten drücken steht in HomeKit jedoch sofort geöffnet und nicht öffnen. 
Ist das so gewollt? 
Mit freundlichen Grüßen 
Jendrik

**Comment by hobbyquaker** [comment]
Szenario: Der Rollladen steht auf 100% - Du drückst die Kachel in der Home App, es wird der Befehl "Fahr auf 0%" gesendet, der Rollladen fährt los. _Irgendwann_ kommt jetzt der nächste Statusreport vom Rollladenaktor mit der aktuellen Position. Drückst Du allerdings erneut auf die Kachel _bevor_ dieser Report kommt wird der Befehl "Fahr auf 100%" gesendet, der aktuelle Zustand ist aber weiterhin fälschlicherweise immer noch auf 100% - es wird "offen" angezeigt da Soll und Ist auf 100% steht. 

Ich teste mal einfach den Ist-Zustand nach einem "Fahr auf 0%" Befehl auf 100-1=99 oder sowas  zu setzen, könnte ne Lösung sein.

**Comment by hobbyquaker** [comment]
@Jemeins mit RedMatic 2.7.1 sollte es jetzt passen. Bitte gib Bescheid ob es so i.O. ist

**Comment by Jemeins** [comment]
Guten Abend,
es funktioniert! 👍 
Vielen Dank für den super Support.
Mit freundlichen Grüßen 
Jendrik
