### ISSUE TITLE
missing homematic-devices/hmip-rcv-50

### ISSUE THREAD

**Issue by ptweety** [HM-RedMatic/RedMatic-HomeKit#126]
Seit Firmware 3.43.15 gibt es auch für HmIP die virtuelle Fernbedienung. RedMatic meldet im Log dazu missing homematic-devices/hmip-rcv-50 und zeigt diese als HmIP device im HomeKit Node an.

Sonderbehandlung erforderlich oder aus der Liste rauswerfen?

**Comment by hobbyquaker** [comment]
muss in die Listen mit den ignorierten devices rein.
