### ISSUE TITLE
Accessoires Raumzuordnung

### ISSUE THREAD

**Issue by spiu16** [HM-RedMatic/RedMatic-HomeKit#127]
Hallo,

Ist es eigentlich möglich die Geräte bereits mit den korrekten Räumen zu initialisieren? Kann das irgendwo im HomeKit-Node eingestellt werden?

Danke und Gruß

**Comment by hobbyquaker** [comment]
nein, die Bridge hat kein Einfluss darauf, Raumzuordnungen und Umbenennungen existieren nur innerhalb von iOS/iCloud.

**Comment by spiu16** [comment]
Ok Danke
