### ISSUE TITLE
Home Assistant Integration

### ISSUE THREAD

**Issue by drMaxxi** [HM-RedMatic/RedMatic-HomeKit#339]
Ich versuche grad e die Raspberrymatic in den Home Assistant zu integrieren. Allerdings scheitert das hauptsächlich daran, weil die Datei config.txt im Ordner /mnt/boot nicht existiert. Ich habe zwar einen Ordner /mnt aber darin befindet sich kein Unterordner boot. Was kann ich tun, um die Installation fortzusetzen?

Herzlichen Dank.

**Comment by ptweety** [comment]
Da bist du hier aber falsch.

**Comment by drMaxxi** [comment]
Ups, sorry
