### ISSUE TITLE
Bridge nicht erreichbar 

### ISSUE THREAD

**Issue by Tom1802** [HM-RedMatic/RedMatic-HomeKit#362]
Hallo,
ich habe die neue HomeKit Architektur und einen HomePod mit neuster Firmware. Seit dem ist meine Redmatic Bridge in HomeKit nicht mehr erreichbar. Ich habe die Bridge bereits entfernt und bei hinzugefügt und auch in der Raspberrymatic komplett neu aufgesetzt.

**Comment by Buddy1344** [comment]
Ich habe das selbe Problem bei meiner CCU3.

**Comment by ptweety** [comment]
Könnt ihr beide mal testen, ob sich der Node `node-red-contrib-homekit-bridged` installieren lässt?
- https://nrchkb.github.io/wiki/introduction/quick-start/#how-to-install

Wenn ja, dann mal zwei neue Bridges anlegen und dort jeweils unterschiedliche Advertiser wählen:
- https://nrchkb.github.io/wiki/nodes/host-node/#advertiser
- Bonjour
- Ciao

Denn jeweils für diese Bridges ein gleichartiges Accessory anlegen. Etwa einen Schalter ...

Wenn beide funktionieren gut. Dann könnte es an der veralteten Version von `hap-nodejs` von RedMatic-Homekit liegen
- https://github.com/homebridge/HAP-NodeJS
- https://github.com/rdmtc/RedMatic-HomeKit/blob/d5b86ff0e82437341929fcff268cc4c81e2041ab/package.json#L38

**Comment by Tom1802** [comment]
Ich hab das Problem am Wochenende lösen können. Es lag bei mir tatsächlich daran, dass der HomePod als Steuerzentrale mit einem AccessPoint im Netzwerk verbunden war, welcher sich zeitweise nicht im engeren Netzwerk befand. Komisch ist nur, dass meine Shelly’s usw. Trotzdem alle angezeigt worden sind.
