### ISSUE TITLE
New Homekit Architecture supported? 

### ISSUE THREAD

**Issue by bekaxe** [HM-RedMatic/RedMatic-HomeKit#366]
Hi all, 

can someone tell me if it is safe to update on Apple to the new homekit architecture? 
Will the bridge then still work? Or can someone recommend an alternative solution? 

Thanks a lot for your help. 
Axel

**Comment by drsnuggles1982** [comment]
Follow this topic

**Comment by dehsgr** [comment]
I did the upgrade with no issue.

**Comment by bekaxe** [comment]
Thank you, upgraded as well without any issues.
