### ISSUE TITLE
implement special Homematic GarageDoorOpener accessory

### ISSUE THREAD

**Issue by hobbyquaker** [HM-RedMatic/RedMatic-HomeKit#42]
benötigt 2 Devices: Ein Tür-Fenster-Kontakt und einen Schaltaktor.

**Comment by spiu16** [comment]
Hallo,
endlich eine HomeKit-Bridge die funktioniert wie sie soll! 👍 
Zu dem GarageDoorOpener: 
Ich habe bei mir für die Steuerung des Garagentores zwei Relais-Kontakte (Offen/Geschlossen) über HM-Wired Schließerkontakte angeschlossen sowie zwei Schaltaktoren (Garagentor auf Offen fahren/Garagentor auf Geschlossen) über HM-Wired 12/7-Aktoren angeschlossen. Damit kann ich gezielt ansteuern, in welche Position das Garagentor fahren soll.
Es wäre daher schön, wenn das in die Funktion mit einfließen kann, sodass zwei Sensoren und zwei Aktoren angesprochen werden können. 
Schon mal danke vorab und weiter so!
Gruß Sven

**Comment by habeck76** [comment]
Hallo hobbyquaker,
erstmal Respekt für deine Arbeit. Echt Top!!
Vielleicht könntest du mir mit dem GarageDoorOpener mal helfen. In meinem Flow funktioniert die Anbindung an den Garagentaster in der CCu super. Leider bekomme ich den CurrentDoorState aus meinem Fensterkontakt nicht richtig übergeben und langsam verzweifele ich gerade.
Danke

**Comment by hobbyquaker** [comment]
Ja

**Comment by habeck76** [comment]
Danke! Hat sich erledigt. Läuft jetzt super! Nur meine Cuxd-Dimmaktoren funktionieren nicht im Homekit. Bist du da noch dran?

**Comment by habeck76** [comment]
Als HM-LC-Dim1TPBU-FM

**Comment by hobbyquaker** [comment]
insofern der kanal 1 ein LEVEL datenpunkt hat sollte das eigtl funktionieren. Oder hat das Gerät mehr als einen Kanal?

**Comment by habeck76** [comment]
Ja, haben die. Level auf Kanal 2

**Comment by habeck76** [comment]
Das sind Hue-Gruppen, die über das Hue-Addon (nicht Kopplung) in die CCU eingebunden sind. Wegen der bidirektionalen Kommunikation. Bei deiner Konkurrenz ;-) konnte man nur den einen Level-Kanal ans Homekit übertragen und dann lief das.

**Comment by spiu16** [comment]
> Danke! Hat sich erledigt. Läuft jetzt super! Nur meine Cuxd-Dimmaktoren funktionieren nicht im Homekit. Bist du da noch dran?

Könntest Du mal deinen Flow posten? Würde mich interessieren, da ich die Einrichtung noch nicht korrekt hinbekommen habe :)
Danke

**Comment by spiu16** [comment]
Könnte mir irgendjemand, bei dem der GarageDoorOpener korrekt funktioniert, bitte mal seinen Flow mit den Einstellungen posten? Danke vorab :)

**Comment by hobbyquaker** [comment]
@spiu16 

> Ich habe bei mir für die Steuerung des Garagentores zwei Relais-Kontakte (Offen/Geschlossen) über HM-Wired Schließerkontakte angeschlossen sowie zwei Schaltaktoren (Garagentor auf Offen fahren/Garagentor auf Geschlossen) über HM-Wired 12/7-Aktoren angeschlossen. Damit kann ich gezielt ansteuern, in welche Position das Garagentor fahren soll.

Wie genau erfolgt bei Dir die Ansteuerung? Schaltest Du die Ausgänge des 12/7 nur für einen Moment an oder müssen die an bleiben bis das Tor ans Ende gefahren ist?

**Comment by spiu16** [comment]
Die Ausgänge habe ich mit virtuellen Schaltern verknüpft. Diese sind als Taster (ein, gleich wieder aus) definiert. Es reicht daher ein Impuls zum Auslösen der Fahrten.

**Comment by hobbyquaker** [comment]
@spiu16 magst Du mal vorab testen? Dazu müsstest Du die Dateien `package.json`, `nodes/redmatic-homekit-homematic-garage.html` und `nodes/redmatic-homekit-homematic-garage.js` hier aus dem Repo nach `/usr/local/addons/redmatic/var/node_modules/redmatic-homekit` kopieren und Node-RED neustarten.

**Comment by spiu16** [comment]
@hobbyquaker package.json in o.g. Verzeichnis und die beiden html/js in Unterverzeichnis /nodes, oder?

**Comment by dehsgr** [comment]
@hobbyquaker ich habe gerade den Commit gesehen. Dann könnte ich meine manuelle Config ja glatt rauswerfen. Super! Klappt das denn anstelle mit dem TFK auch mit dem HM-Sec-TiS?

**Comment by hobbyquaker** [comment]
Jup, alles was ein STATE oder MOTION Datenpunkt hat sollte gehen (Tür/Fensterkontakte, HM-Sec-TIS, Eingänge von 12/7 oder 12/14, Schließerkontaktschnittstellen, HmIP-SAM, ...)

**Comment by hobbyquaker** [comment]
RedMatic 2.7.0 ist grad in der Mache, da steckt das drin.

**Comment by hobbyquaker** [comment]
Gebt dann bitte bei Gelegenheit Bescheid ob alles so funktioniert wie es soll :)

**Comment by spiu16** [comment]
Also grundsätzlich schonmal super als eigenes Accessory.
Folgendes Feedback:
- Bei Eingabe der Sensoren kommen keine "Eingabevorschläge" (bei den Aktoren dagegen schon)
- Wenn Garagentor geöffnet wird "Geöffnet" angezeigt (Text), aber Symbol ist geschlossen.
- Wenn Garagentor geschlossen wird "Geöffnet" angezeigt (Text), aber Symbol ist geschlossen.
Irgendwas passt da noch nicht ;-) Aber ich bin sicher @hobbyquaker kriegt das hin :)

**Comment by rauchmandl** [comment]
Hallo erstmal, 

hab mich extra angemeldet um dir zu danken(DANKE) und einen Stern zu hinterlassen. 

Habe 4 Garagentore, pro Tor 1 Aktor und 1 Sensor(geschlossen). Funktionieren nun alle einwandfrei.
Sowohl die Anzeige von geöffnet/geschlossen, als auch die Animation arbeiten fehlerfrei.

Thanx a lot

**Comment by hobbyquaker** [comment]
> Bei Eingabe der Sensoren kommen keine "Eingabevorschläge" (bei den Aktoren dagegen schon)
Ich vermute Du nutzt HMW-Sen-SC-*? Die hatte ich vergessen, deren Datenpunkte heissen `SENSOR` und nicht `STATE`. Ist ergänzt und mit dem nächsten Release gefixt.

> Wenn Garagentor geöffnet wird "Geöffnet" angezeigt (Text), aber Symbol ist geschlossen.
> Wenn Garagentor geschlossen wird "Geöffnet" angezeigt (Text), aber Symbol ist geschlossen.

Das ist seltsam. Du nutzt die Home App? Ich hab da kein Einfluss auf Text/Bild, es gibt die Zustände:
* Text: "Geschlossen", Bild: geschlossenes Tor
* Text: "Wird geöffnet", Bild: offenes Tor
* Text: "Geöffnet", Bild: offenes Tor
* Text: "Schließen", Bild: offenes Tor

**Comment by spiu16** [comment]
> Ich vermute Du nutzt HMW-Sen-SC-*? Die hatte ich vergessen, deren Datenpunkte heissen `SENSOR` und nicht `STATE`. Ist ergänzt und mit dem nächsten Release gefixt.

Ja genau, HMW-Sen-SC-12.

> Das ist seltsam. Du nutzt die Home App?

Ja, Home App. Ich teste mal wie es sich verhält wenn ich statt 2 Sensoren/Aktoren jeweils nur einen verwende.

**Comment by spiu16** [comment]
@hobbyquaker 

> Ich vermute Du nutzt HMW-Sen-SC-*? Die hatte ich vergessen, deren Datenpunkte heissen `SENSOR` und nicht `STATE`. Ist ergänzt und mit dem nächsten Release gefixt.

kann es sein dass deshalb die Sensoren nicht erkannt werden?

**Comment by hobbyquaker** [comment]
> kann es sein dass deshalb die Sensoren nicht erkannt werden?

🤦‍♂️ oh - ja klar. Gib mir ein paar Minuten, neues Release ist auf dem Weg ;)

**Comment by spiu16** [comment]
👍

**Comment by hobbyquaker** [comment]
So, mit RedMatic 2.7.1 sollte es gehen. Hab jetzt auch Klarheit was die Zustände von Text/Bild angeht. Wenn man mit 2 Sensoren arbeitet und in einem Zwischenzustand hängt (weder offen noch zu) dann kommt es dazu dass das Bild ein geschlossenes Tor zeigt aber der Text "geöffnet" ist. Und umgekehrt. Ergibt in dem Fall auch Sinn denke ich.

**Comment by spiu16** [comment]
Auch wenn die Nachbarn sich vielleicht wundern warum unser Garagentor abends um 21:30 Uhr mehrfach auf und zu geht: Es funktioniert! :+1: 
Das einzige was ich nochmal beobachten muss ist das Verhalten wenn das Garagentor "extern" (also z.B. mit Funkfernbedienung) bedient wird.
Aber schon mal vielen Dank!!!

**Comment by hobbyquaker** [comment]
Ich schließe hier mal. Falls es noch Probleme/Optimierungsbedarf gibt am besten neuen Issue aufmachen.
