### ISSUE TITLE
Einbinden von HM-Sen-DB-PCB

### ISSUE THREAD

**Issue by Jemeins** [HM-RedMatic/RedMatic-HomeKit#79]

**Comment by hobbyquaker** [comment]
Bin mir nicht mehr ganz schlüssig ob es sinnvoll ist dieses Gerät automatisch anzulegen. Die Home App/Siri wissen mit einem Standalone DoorBell Service nichts anzufangen, der macht eigentlich nur Sinn in Verbindung mit einem Camera Service damit man einen Push Nachricht mit Bild erhält wenn es klingelt. Außerdem kann man den DoorBell Service auch komfortabel mit dem Universal Accessory anlegen.

**Comment by Jemeins** [comment]
Moin, 
ich habe gehört, dass man den DoorBell Service auch ohne Kamera nutzen kann, indem man eine Klingel mit einem Bewegungsmelder kombiniert. Ist es möglich das man den Bewegungsmelder auf der CCU emu­lie­rt?

**Comment by Jemeins** [comment]
Ich habe es heute mit dem Universal Accessory versucht, bin jedoch gescheitert. Kannst du mir ein Beispiel geben wie ich den Klingelsensor mit dem Universal Accessory nutzen kann?
