### ISSUE TITLE
Dimmwerte und Szenen

### ISSUE THREAD

**Issue by YuriBiemanov** [HM-RedMatic/RedMatic-HomeKit#87]
Guten Morgen,

Mir fällt auf, dass Szenen, in denen geringe Dimmwerte (<30%) eingeschaltet werden sollen nicht zuverlässig diese Werte ansteuern. Anstelle den Dimmwert zu schalten werden 100% geschaltet. Die Szene wird in HK dann auch nicht als aktiv markiert.

Dimmer aus (0%)
Szene mit Dimmwert 25%
Dimmer schaltet ein mit 100% (normal bei HM, danach regelt Dimmer runter)
Szene wird in HK kurz als aktiv markiert,
Dimmer bleibt bei 100%
Szene wird in HK als nicht aktiv markiert 

Wenn der Dimmer bereits eingeschaltet war funktioniert es.

**Comment by hobbyquaker** [comment]
@YuriBiemanov kannst Du mal testen ob das mit der RedMatic Version 1.10.5 nun funktioniert?

**Comment by YuriBiemanov** [comment]
Hallo, 

Es funktioniert nun tadellos! Saubere Arbeit!

Gruß und Danke!
