### ISSUE TITLE
implement hm-lc-rgbw-wm / hb-uni-rgb-led-ctrl

### ISSUE THREAD

**Issue by hobbyquaker** [HM-RedMatic/RedMatic-HomeKit#91]

**Comment by hobbyquaker** [comment]
Will das irgendwer? :-)

**Comment by hobbyquaker** [comment]
@jp112sdl versteh ich das richtig dass der `COLOR` Datenpunkt auf Kanal 2 den Hue-Wert im Bereich 0-199 angibt? D.h. 0=Rot, 199=Rot? Und 200 ist Weiss? Und Saturation gibts gar nicht?

**Comment by jp112sdl** [comment]
Ja, das siehst du genau richtig.
