### ISSUE TITLE
Erweiterte Gerätekonfiguration

### ISSUE THREAD

**Issue by hobbyquaker** [HM-RedMatic/RedMatic-HomeKit#93]
- [x] Mehrkanal-Schaltaktoren als ein Multi-Service-Accessory oder als mehrere Accessories erzeugen
- [x] Bei Homematic Kanaltyp Switch Auswahl für Service anbieten: ~~(TBD: alternativ als spezielles Homematic Switch Accessory anbieten und im Homematic Node weiterhin immer Switch Service nutzen?)~~
  * Fan 
  * Valve
  * Valve mit ValveType Irrigation
  * Lightbulb
  * Outlet ~~(inUse Characteristic bei Schaltaktoren mit Leistungsmessung ab überschreitung einer konfigurierbaren Leistung setzen)~~
  * Switch
- [x]  einfach gleich alle Geräte mit Leistungsmessung default als Outlet anlegen 
- [x] Bei Homematic Kanaltyp SHUTTER_CONTACT Auswahl für Service anbieten: (TBC, ist das nötig?)
  * Door
  * Window
  * ContactSensor 
  _Eigentlich sollte das nicht nötig sein. Man kann auch beim ContactSensor ein Tür oder Fenster Icon einstellen. Problem beim Abbilden eines SHUTTER_CONTACT als Window oder Door Service: Die Kachel sieht aus als ob man sie bedienen könnte - obwohl das gar nicht geht. Find ich unschön._

**Comment by ptweety** [comment]
Bzgl. der Leistungsschwelle mal ne Frage: welchen UseCase magst du damit denn abbilden?

Meine Vorstellung geht in die Richtung: erkenne, wenn Waschmaschine, Trockner oder Spülmaschine fertig sind. Da braucht es dann aber öfter mal mehrere Schwellen (waschen, Pause, waschen, Pause, schleudern, Pause, schleudern, ...) oder man will erst eine Nachricht, wenn eine Schwelle für eine gewisse Zeit über-/unterschritten ist (Pause >5min).

**Comment by hobbyquaker** [comment]
Hatte gedacht man könnte HomeKit Automationen über die `isUse` Charakteristik triggern, eben nachgeschaut, das geht garnicht. Scheint so als ob das zu nichts weiter nütze ist als es in den Einstellungen des Services anzuzeigen. Ich denke ich streich den Punkt. Wenn Du eine Fertigmeldung implementieren willst musst das eh außerhalb von HomeKit bewerkstelligen.
