### ISSUE TITLE
Heizungsgruppe in Homekit mit Boost

### ISSUE THREAD

**Issue by ptweety** [HM-RedMatic/RedMatic-HomeKit#96]
Hi zusammen,

ich habe 2 HmIP-eTRV und einen HmIP-WTH-2 in einer Heizungsgruppe. Alle Geräte sehe ich in RedMatic im Homematic Node gelistet (inkl HmIP-HEATING für die Gruppe), aber nur die echten Geräte und nicht die virtuelle Gruppe können in Homekit angezeigt werden. Daher habe ich bisher nur den WTH-2 aktiviert.

Wenn ich den Boost in Homekit aktiviere, dann wird der an den WHT-2 übertragen (Zeit tickt runter), aber die anderen Geräte in der Heizungsgruppe bekommen davon nichts mit. Direkt am Gerät und aus der WebUI via Heizungsgruppe überträgt sich auch der Boost an die eTRV korrekt.

Ist das ein Bug in RedMatic oder fehlt einfach nur das zusätzliche Gerät HmIP-HEATING, um alles gemeinsam zu steuern?

**Comment by hobbyquaker** [comment]
Bin mir doch etwas unschlüssig ob es sinnvoller ist die Gruppen zu integrieren oder ob ich doch lieber was Einbau dass beim Aktivieren des Boost an einem Thermostaten auch ein Befehl an alle verknüpften Heizungen gesendet wird.
Problem bei den Gruppen: Ich kann nicht (mit vertretbarem Aufwand) auslesen welche Geräte Teil der Gruppe sind und somit kann ich nicht nachschauen ob irgendeine Heizung grade aufgedreht ist. Das brauch ich aber damit in der Home App dieser Kreis grün oder rot angezeigt wird je nachdem ob im Moment geheizt wird oder nicht.

**Comment by ptweety** [comment]
Hm, ich bin noch bei 1.10.5 und konnte noch nicht den upgrade machen. Beim rumspielen an der Heizung ist mir aber zusätzlich noch bewusst geworden, dass nicht nur der Boss nicht in die Gruppe weitergereicht wird, sondern auch die anderen Einstellungen am WTH-2 nicht an die restlichen Geräte der Gruppe durchgereicht werden.

Wenn das nun für Boost gelöst ist, gehe ich davon aus, dass dies dann auch für die anderen Kanäle umgesetzt werden müsst.

Ich kann ja auch selber mal was basteln, bräuchte da aber ein wenig Hilfe, wie ich die Kanäle der Gruppe analysieren kann. Da fehlt mir noch das Wissen.

**Comment by hobbyquaker** [comment]
> dass nicht nur der Boost nicht in die Gruppe weitergereicht wird, sondern auch die anderen Einstellungen am WTH-2 nicht an die restlichen Geräte der Gruppe durchgereicht werden.

Doch, die sollten weitergegeben werden insofern eine Direktverknüpfung besteht. Funktioniert bei mir zumindest. Passiert allerdings nicht sofort sondern dauert bis zu 180sek iirc.

**Comment by ptweety** [comment]
Ah, so geduldig war ich jetzt nicht. Gibt es da einen Grund für die Verzögerung? Das fällt ja normalerweise niemandem auf (wer schaltet schon seine Heizung im selben Raum per Smartphone, wenn man das auch direkt machen kann?)

Zumindest der Boost funktioniert mit der Anpassung m.E. einwandfrei. Daher könnte der Issue geschlossen werden.

**Comment by ptweety** [comment]
@hobbyquaker können wir hier doch wieder aufmachen?

Ich habe jetzt mal getestet, wie das mit nur zwei Thermostaten (HmIP-eTRV) in einer Gruppe ist (also ohne WTH). Im Prinzip funktioniert alles bis auf eine Sache: durch die Gruppe entstehen ja Direktverknüpfungen zw. den Thermostaten. Durch Bedienung der Gruppe und auch am Gerät werden beide Thermostate umgestellt.

Nur über HomeKit ist das nicht der Fall. Hier ist jedes Thermostat einzeln aufgeführt und auch separat steuerbar. Wenn man die Thermostate in HomeKit gruppieren könnte, wäre das ja kein Ding. Aber das geht leider auch nicht.

**Comment by hobbyquaker** [comment]
Da komme ich wohl doch nicht drum rum Unterstützung für die Heizungsgruppen einzubauen. Gib mir ein wenig Zeit dafür, die Gruppen sind leider etwas "sperrig" in der Handhabung ;-)
Ich schließe hier mal, neuer Issue dafür: #131
